name: CI Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # clone
      - name: Use Node.js 20.x # node 환경 구성 
        uses: actions/setup-node@v4 # import 
        with:
          node-version: 20.x
          cache: "npm" # 필요한 거 설치 
      - run: npm ci

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 # vm 위에 docker 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub # docker hub 로그인 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # env 파일에 숨겨서 넣음 
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t dweblab/songdo .

      - name: Push docker image # 빌드된 이미지 push 
        run: docker push eunji113/inu:latest